language: php
php:
  - 7.2
  - 7.3

services:
  - postgresql

cache:
  directories:
    - $HOME/.composer/cache

notifications:
  email:
    on_failure: always
    on_success: change
  slack: davenel:B2FTmjvgP51RNWcw1nChPj1z

before_script:
  - composer install --no-progress --no-interaction --prefer-dist --no-suggest
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp .env.travis .env
  - php artisan key:generate
  - php artisan migrate:fresh

script:
  - vendor/bin/phpunit
