<?php

namespace Tests\Unit;

use App\Models\Agent;
use App\Models\Groupe;
use App\Services\GroupeService;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

class GroupeServiceTest extends TestCase
{
    use WithFaker;
    use RefreshDatabase;

    private $service;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->service = new GroupeService();
    }

    /**
     * A basic unit test example.
     *
     * @return void
     */
    public function testCreateGroupe()
    {
        $libelle = $this->faker->word;
        $description = $this->faker->sentence;

        $groupe = $this->service->create($libelle, $description);

        $this->assertInstanceOf(Groupe::class, $groupe);
        $this->assertEquals($libelle, $groupe->libelle);
        $this->assertEquals($description, $groupe->description);
    }

    public function testUpdateLibelleGroupe()
    {
        $libelle = $this->faker->word;

        $groupe = factory(Groupe::class)->create();

        $upd_groupe = $this->service->update($groupe, $libelle);

        $this->assertInstanceOf(Groupe::class, $upd_groupe);
        $this->assertEquals($libelle, $upd_groupe->libelle);
    }

    public function testUpdateDescriptionGroupe()
    {
        $description = $this->faker->word;

        $groupe = factory(Groupe::class)->create();

        $upd_groupe = $this->service->update($groupe, null, $description);

        $this->assertInstanceOf(Groupe::class, $upd_groupe);
        $this->assertEquals($description, $upd_groupe->description);
    }

    public function testSetAgents()
    {
        /** @var Groupe $groupe */
        $groupe = factory(Groupe::class)->create();
        $agents = factory(Agent::class, 5)->create()
            ->pluck('id')
            ->all();

        $this->service->setAgents($groupe, $agents);

        $this->assertCount(5, $groupe->agents);
    }
}
