<?php

namespace Tests\Unit;

use App\Models\Agent;
use App\Models\Sms;
use App\Services\SmsService;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

class SmsServiceTest extends TestCase
{
    use RefreshDatabase;
    use WithFaker;

    private $service;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->service = new SmsService();
    }

    public function testCreateSms()
    {
        $contenu = $this->faker->sentence;

        $this->service->create($contenu);

        $this->assertCount(1, Sms::all());
    }

    public function testSetDestinataires()
    {
        $contenu = $this->faker->sentence;
        $agents = factory(Agent::class, 20)->create();

        $this->service->create($contenu);
        $this->service->setDestinataires($agents);


    }
}
