<?php
/**
 * Model object generated by: Skipper (http://www.skipper18.com)
 * Do not modify this file manually.
 */

namespace App\Models\AbstractModels;

use Illuminate\Database\Eloquent\Model;

abstract class AbstractAgent extends Model
{
    /**  
     * Primary key type.
     * 
     * @var string
     */
    protected $keyType = 'bigInteger';
    
    /**  
     * The attributes that should be cast to native types.
     * 
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'nom' => 'string',
        'prenom' => 'string',
        'grade_id' => 'integer',
        'statut' => 'boolean',
        'telephone' => 'string',
        'created_at' => 'datetime',
        'updated_at' => 'datetime'
    ];
    
    /**  
     * The attributes that are mass assignable.
     * 
     * @var array
     */
    protected $fillable = [
        'id',
        'nom',
        'prenom',
        'grade_id',
        'statut',
        'telephone',
        'created_at',
        'updated_at'
    ];
    
    public function grade()
    {
        return $this->belongsTo('\App\Models\Grade', 'grade_id', 'id');
    }
    
    public function sms()
    {
        return $this->belongsToMany('\App\Models\Sms', 'agent_sms', 'agent_id', 'sms_id')->withPivot('auteur');
    }
    
    public function groupes()
    {
        return $this->belongsToMany('\App\Models\Groupe', 'groupe_has_agents', 'agent_id', 'groupe_id');
    }
}
